cmake .. \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DWITH_TINYDTLS=OFF \
  -DDTLS_PROVIDER_TINYDTLS=OFF \
  -DWITH_PRPL=ON \
  -DWITH_PRPL_EASYMESH=ON \
  -DWITH_PRPL_AMBIORIX=ON \
  -DBUILD_TESTS=ON \
  -DENABLE_COVERAGE=ON \
  -DENABLE_SANITIZERS=ON
